#!/bin/bash

# Auto-Build Environment Setup
# Generated by Planner Agent for Git Integration Enhancement

set -e

echo "========================================"
echo "FHIR Mapper - Git Integration Dev Environment"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Wait for service function
wait_for_service() {
    local port=$1
    local name=$2
    local max=60
    local count=0

    echo "Waiting for $name on port $port..."
    while ! nc -z localhost $port 2>/dev/null; do
        count=$((count + 1))
        if [ $count -ge $max ]; then
            echo -e "${RED}$name failed to start${NC}"
            return 1
        fi
        sleep 1
    done
    echo -e "${GREEN}$name ready${NC}"
}

# Check if Docker is running
if ! docker info > /dev/null 2>&1; then
    echo -e "${RED}Docker is not running. Please start Docker Desktop.${NC}"
    exit 1
fi

# ============================================
# START INFRASTRUCTURE (Docker Compose)
# ============================================

echo ""
echo "Starting infrastructure services..."
docker-compose up -d postgres redis azurite fhir-converter-dotnet fhir-validator

# Wait for infrastructure
wait_for_service 5432 "PostgreSQL"
wait_for_service 6379 "Redis"
wait_for_service 8081 "FHIR Converter"
wait_for_service 8083 "FHIR Validator"

# ============================================
# START BACKEND (Spring Boot)
# ============================================

echo ""
echo "Starting backend service..."
cd backend

# Check if Maven is installed
if ! command -v mvn &> /dev/null; then
    echo -e "${RED}Maven not found. Please install Maven.${NC}"
    exit 1
fi

# Start Spring Boot in background
mvn spring-boot:run > ../backend.log 2>&1 &
BACKEND_PID=$!
echo "Backend PID: $BACKEND_PID"

cd ..

wait_for_service 8080 "Backend API"

# ============================================
# START FRONTEND (React + Vite)
# ============================================

echo ""
echo "Starting frontend service..."
cd frontend

# Check if npm is installed
if ! command -v npm &> /dev/null; then
    echo -e "${RED}npm not found. Please install Node.js and npm.${NC}"
    exit 1
fi

# Install dependencies if needed
if [ ! -d "node_modules" ]; then
    echo "Installing frontend dependencies..."
    npm install
fi

# Start Vite dev server in background
npm run dev > ../frontend.log 2>&1 &
FRONTEND_PID=$!
echo "Frontend PID: $FRONTEND_PID"

cd ..

wait_for_service 3000 "Frontend"

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo -e "${GREEN}Environment Ready!${NC}"
echo "========================================"
echo ""
echo "Services:"
echo "  PostgreSQL:      localhost:5432"
echo "  Redis:           localhost:6379"
echo "  Backend API:     http://localhost:8080"
echo "  Frontend:        http://localhost:3000"
echo "  FHIR Converter:  http://localhost:8081"
echo "  FHIR Validator:  http://localhost:8083"
echo ""
echo "Logs:"
echo "  Backend:  tail -f backend.log"
echo "  Frontend: tail -f frontend.log"
echo ""
echo "Swagger UI: http://localhost:8080/swagger-ui.html"
echo ""
echo "To stop services:"
echo "  kill $BACKEND_PID $FRONTEND_PID"
echo "  docker-compose down"
echo ""
echo -e "${YELLOW}Note: This task extends existing Git integration.${NC}"
echo -e "${YELLOW}Test existing push functionality before implementing new features.${NC}"
echo ""
