import { useState, useCallback } from 'react';
import {
  FileText,
  CheckSquare,
  Square,
  MessageSquare,
  MessageCircle,
  Plus,
  X,
  Edit2,
  Trash2,
  User,
  AlertTriangle,
  Info,
  Lightbulb,
  AlertCircle,
} from 'lucide-react';

export type AttachmentType =
  | 'note'
  | 'todo'
  | 'task'
  | 'hyperlink'
  | 'callout'
  | 'label'
  | 'comment'
  | 'image'
  | 'equation';

export type CalloutType = 'info' | 'warning' | 'opportunity' | 'pain_point' | 'critical';
export type TaskPriority = 'urgent' | 'high' | 'normal' | 'low';
export type TaskStatus = 'not_started' | 'in_progress' | 'completed' | 'blocked';

export interface BaseAttachment {
  id: string;
  nodeId: string;
  type: AttachmentType;
  createdAt: Date;
  updatedAt: Date;
  createdBy: string;
}

export interface NoteAttachment extends BaseAttachment {
  type: 'note';
  content: string;
  isAutoGenerated: boolean;
  source?: string;
}

export interface TodoAttachment extends BaseAttachment {
  type: 'todo';
  text: string;
  completed: boolean;
  completedAt?: Date;
  completedBy?: string;
}

export interface TaskAttachment extends BaseAttachment {
  type: 'task';
  title: string;
  description?: string;
  dueDate?: Date;
  assignee?: string;
  priority: TaskPriority;
  status: TaskStatus;
  linkedPlaybookItem?: string;
}

export interface HyperlinkAttachment extends BaseAttachment {
  type: 'hyperlink';
  url: string;
  title: string;
  icon?: string;
  isAutoGenerated: boolean;
}

export interface CalloutAttachment extends BaseAttachment {
  type: 'callout';
  text: string;
  calloutType: CalloutType;
  color: string;
  position: 'top' | 'right' | 'bottom' | 'left';
}

export interface LabelAttachment extends BaseAttachment {
  type: 'label';
  text: string;
  color: string;
  isSystemLabel: boolean;
  category?: string;
}

export interface CommentAttachment extends BaseAttachment {
  type: 'comment';
  text: string;
  author: string;
  timestamp: Date;
  parentCommentId?: string;
}

export interface ImageAttachment extends BaseAttachment {
  type: 'image';
  url: string;
  thumbnailUrl: string;
  alt: string;
  width: number;
  height: number;
  source?: string;
}

export interface EquationAttachment extends BaseAttachment {
  type: 'equation';
  formula: string;
  variables: Record<string, number | string>;
  result: number | string;
  displayFormat: string;
}

export type Attachment =
  | NoteAttachment
  | TodoAttachment
  | TaskAttachment
  | HyperlinkAttachment
  | CalloutAttachment
  | LabelAttachment
  | CommentAttachment
  | ImageAttachment
  | EquationAttachment;

export interface AttachmentPanelProps {
  nodeId: string;
  nodeLabel: string;
  attachments: Attachment[];
  onAddAttachment: (nodeId: string, type: AttachmentType, data: Partial<Attachment>) => void;
  onUpdateAttachment: (attachmentId: string, data: Partial<Attachment>) => void;
  onDeleteAttachment: (attachmentId: string) => void;
  onClose: () => void;
}

interface TabButtonProps {
  active: boolean;
  icon: React.ReactNode;
  label: string;
  count: number;
  onClick: () => void;
}

function TabButton({ active, icon, label, count, onClick }: TabButtonProps) {
  return (
    <button
      onClick={onClick}
      className={`flex items-center gap-1.5 px-3 py-2 text-sm font-medium rounded-t-md transition-colors
        ${active
          ? 'bg-gray-800 text-white border-b-2 border-blue-500'
          : 'text-gray-400 hover:text-gray-200 hover:bg-gray-800/50'
        }`}
    >
      {icon}
      <span>{label}</span>
      {count > 0 && (
        <span className={`px-1.5 py-0.5 text-xs rounded-full ${active ? 'bg-blue-600' : 'bg-gray-700'}`}>
          {count}
        </span>
      )}
    </button>
  );
}

export function AttachmentPanel({
  nodeId,
  nodeLabel,
  attachments,
  onAddAttachment,
  onUpdateAttachment,
  onDeleteAttachment,
  onClose,
}: AttachmentPanelProps) {
  const [activeTab, setActiveTab] = useState<'notes' | 'todos' | 'tasks' | 'links' | 'callouts' | 'labels' | 'comments'>('notes');
  const [editingId, setEditingId] = useState<string | null>(null);
  const [newItemContent, setNewItemContent] = useState('');

  const notes = attachments.filter((a): a is NoteAttachment => a.type === 'note');
  const todos = attachments.filter((a): a is TodoAttachment => a.type === 'todo');
  // Tasks, hyperlinks, and labels tabs not implemented yet - will be added in Phase E
  const callouts = attachments.filter((a): a is CalloutAttachment => a.type === 'callout');
  const comments = attachments.filter((a): a is CommentAttachment => a.type === 'comment');

  const handleAddNote = useCallback(() => {
    if (!newItemContent.trim()) return;
    onAddAttachment(nodeId, 'note', {
      content: newItemContent,
      isAutoGenerated: false,
    });
    setNewItemContent('');
  }, [nodeId, newItemContent, onAddAttachment]);

  const handleAddTodo = useCallback(() => {
    if (!newItemContent.trim()) return;
    onAddAttachment(nodeId, 'todo', {
      text: newItemContent,
      completed: false,
    });
    setNewItemContent('');
  }, [nodeId, newItemContent, onAddAttachment]);

  const handleToggleTodo = useCallback((todo: TodoAttachment) => {
    onUpdateAttachment(todo.id, {
      completed: !todo.completed,
      completedAt: !todo.completed ? new Date() : undefined,
    });
  }, [onUpdateAttachment]);

  const handleAddCallout = useCallback((calloutType: CalloutType) => {
    if (!newItemContent.trim()) return;
    onAddAttachment(nodeId, 'callout', {
      text: newItemContent,
      calloutType,
      color: getCalloutColor(calloutType),
      position: 'right',
    });
    setNewItemContent('');
  }, [nodeId, newItemContent, onAddAttachment]);

  const handleAddComment = useCallback(() => {
    if (!newItemContent.trim()) return;
    onAddAttachment(nodeId, 'comment', {
      text: newItemContent,
      author: 'Current User', // Replace with actual user
      timestamp: new Date(),
    });
    setNewItemContent('');
  }, [nodeId, newItemContent, onAddAttachment]);

  return (
    <div className="w-80 bg-gray-900 border-l border-gray-700 flex flex-col h-full">
      {/* Header */}
      <div className="flex items-center justify-between px-4 py-3 border-b border-gray-700">
        <div className="flex flex-col">
          <span className="text-xs text-gray-500 uppercase">Attachments</span>
          <span className="text-sm font-medium text-white truncate max-w-[200px]">{nodeLabel}</span>
        </div>
        <button
          onClick={onClose}
          className="p-1 text-gray-400 hover:text-white hover:bg-gray-800 rounded"
        >
          <X className="w-4 h-4" />
        </button>
      </div>

      {/* Tabs */}
      <div className="flex items-center gap-1 px-2 pt-2 border-b border-gray-700 overflow-x-auto">
        <TabButton
          active={activeTab === 'notes'}
          icon={<FileText className="w-4 h-4" />}
          label="Notes"
          count={notes.length}
          onClick={() => setActiveTab('notes')}
        />
        <TabButton
          active={activeTab === 'todos'}
          icon={<CheckSquare className="w-4 h-4" />}
          label="To-Dos"
          count={todos.length}
          onClick={() => setActiveTab('todos')}
        />
        <TabButton
          active={activeTab === 'callouts'}
          icon={<MessageSquare className="w-4 h-4" />}
          label="Callouts"
          count={callouts.length}
          onClick={() => setActiveTab('callouts')}
        />
        <TabButton
          active={activeTab === 'comments'}
          icon={<MessageCircle className="w-4 h-4" />}
          label="Comments"
          count={comments.length}
          onClick={() => setActiveTab('comments')}
        />
      </div>

      {/* Content */}
      <div className="flex-1 overflow-y-auto p-3">
        {activeTab === 'notes' && (
          <div className="space-y-3">
            {notes.map((note) => (
              <div
                key={note.id}
                className="p-3 bg-gray-800 rounded-md border border-gray-700"
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex-1">
                    {editingId === note.id ? (
                      <textarea
                        defaultValue={note.content}
                        className="w-full p-2 bg-gray-700 border border-gray-600 rounded text-sm text-gray-200 focus:outline-none focus:border-blue-500"
                        rows={4}
                        onBlur={(e) => {
                          onUpdateAttachment(note.id, { content: e.target.value });
                          setEditingId(null);
                        }}
                        autoFocus
                      />
                    ) : (
                      <p className="text-sm text-gray-300 whitespace-pre-wrap">{note.content}</p>
                    )}
                  </div>
                  <div className="flex items-center gap-1">
                    <button
                      onClick={() => setEditingId(note.id)}
                      className="p-1 text-gray-500 hover:text-gray-300"
                    >
                      <Edit2 className="w-3 h-3" />
                    </button>
                    <button
                      onClick={() => onDeleteAttachment(note.id)}
                      className="p-1 text-gray-500 hover:text-red-400"
                    >
                      <Trash2 className="w-3 h-3" />
                    </button>
                  </div>
                </div>
                {note.isAutoGenerated && (
                  <div className="mt-2 text-xs text-gray-500">
                    Auto-generated from {note.source || 'system'}
                  </div>
                )}
              </div>
            ))}

            {/* Add Note Input */}
            <div className="pt-2">
              <textarea
                value={newItemContent}
                onChange={(e) => setNewItemContent(e.target.value)}
                placeholder="Add a note..."
                className="w-full p-2 bg-gray-800 border border-gray-700 rounded text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500"
                rows={3}
              />
              <button
                onClick={handleAddNote}
                disabled={!newItemContent.trim()}
                className="mt-2 flex items-center gap-1 px-3 py-1.5 text-sm bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 disabled:text-gray-500 text-white rounded transition-colors"
              >
                <Plus className="w-4 h-4" />
                Add Note
              </button>
            </div>
          </div>
        )}

        {activeTab === 'todos' && (
          <div className="space-y-2">
            {todos.map((todo) => (
              <div
                key={todo.id}
                className={`flex items-start gap-2 p-2 rounded-md hover:bg-gray-800/50 ${todo.completed ? 'opacity-60' : ''}`}
              >
                <button
                  onClick={() => handleToggleTodo(todo)}
                  className="mt-0.5 text-gray-400 hover:text-blue-400"
                >
                  {todo.completed ? (
                    <CheckSquare className="w-4 h-4 text-green-500" />
                  ) : (
                    <Square className="w-4 h-4" />
                  )}
                </button>
                <span className={`flex-1 text-sm ${todo.completed ? 'line-through text-gray-500' : 'text-gray-200'}`}>
                  {todo.text}
                </span>
                <button
                  onClick={() => onDeleteAttachment(todo.id)}
                  className="p-1 text-gray-500 hover:text-red-400"
                >
                  <Trash2 className="w-3 h-3" />
                </button>
              </div>
            ))}

            {/* Add Todo Input */}
            <div className="pt-2 flex items-center gap-2">
              <input
                type="text"
                value={newItemContent}
                onChange={(e) => setNewItemContent(e.target.value)}
                onKeyDown={(e) => e.key === 'Enter' && handleAddTodo()}
                placeholder="Add a to-do..."
                className="flex-1 px-3 py-1.5 bg-gray-800 border border-gray-700 rounded text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500"
              />
              <button
                onClick={handleAddTodo}
                disabled={!newItemContent.trim()}
                className="p-1.5 bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 text-white rounded transition-colors"
              >
                <Plus className="w-4 h-4" />
              </button>
            </div>
          </div>
        )}

        {activeTab === 'callouts' && (
          <div className="space-y-3">
            {callouts.map((callout) => (
              <div
                key={callout.id}
                className={`p-3 rounded-md border-l-4 ${getCalloutStyles(callout.calloutType)}`}
              >
                <div className="flex items-start justify-between gap-2">
                  <div className="flex items-start gap-2">
                    {getCalloutIcon(callout.calloutType)}
                    <span className="text-sm text-gray-200">{callout.text}</span>
                  </div>
                  <button
                    onClick={() => onDeleteAttachment(callout.id)}
                    className="p-1 text-gray-500 hover:text-red-400"
                  >
                    <Trash2 className="w-3 h-3" />
                  </button>
                </div>
                <div className="mt-1 text-xs text-gray-500 capitalize ml-6">
                  {callout.calloutType.replace('_', ' ')}
                </div>
              </div>
            ))}

            {/* Add Callout */}
            <div className="pt-2 space-y-2">
              <textarea
                value={newItemContent}
                onChange={(e) => setNewItemContent(e.target.value)}
                placeholder="Add a callout..."
                className="w-full p-2 bg-gray-800 border border-gray-700 rounded text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500"
                rows={2}
              />
              <div className="flex flex-wrap gap-1">
                <button
                  onClick={() => handleAddCallout('info')}
                  disabled={!newItemContent.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-blue-600/20 text-blue-400 hover:bg-blue-600/30 disabled:opacity-50 rounded"
                >
                  <Info className="w-3 h-3" /> Info
                </button>
                <button
                  onClick={() => handleAddCallout('warning')}
                  disabled={!newItemContent.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-yellow-600/20 text-yellow-400 hover:bg-yellow-600/30 disabled:opacity-50 rounded"
                >
                  <AlertTriangle className="w-3 h-3" /> Warning
                </button>
                <button
                  onClick={() => handleAddCallout('opportunity')}
                  disabled={!newItemContent.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-green-600/20 text-green-400 hover:bg-green-600/30 disabled:opacity-50 rounded"
                >
                  <Lightbulb className="w-3 h-3" /> Opportunity
                </button>
                <button
                  onClick={() => handleAddCallout('pain_point')}
                  disabled={!newItemContent.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-orange-600/20 text-orange-400 hover:bg-orange-600/30 disabled:opacity-50 rounded"
                >
                  <AlertCircle className="w-3 h-3" /> Pain Point
                </button>
                <button
                  onClick={() => handleAddCallout('critical')}
                  disabled={!newItemContent.trim()}
                  className="flex items-center gap-1 px-2 py-1 text-xs bg-red-600/20 text-red-400 hover:bg-red-600/30 disabled:opacity-50 rounded"
                >
                  <AlertTriangle className="w-3 h-3" /> Critical
                </button>
              </div>
            </div>
          </div>
        )}

        {activeTab === 'comments' && (
          <div className="space-y-3">
            {comments.map((comment) => (
              <div
                key={comment.id}
                className="p-3 bg-gray-800 rounded-md"
              >
                <div className="flex items-start justify-between">
                  <div className="flex items-center gap-2 mb-1">
                    <User className="w-3 h-3 text-gray-500" />
                    <span className="text-xs font-medium text-gray-400">{comment.author}</span>
                    <span className="text-xs text-gray-600">
                      {new Date(comment.timestamp).toLocaleDateString()}
                    </span>
                  </div>
                  <button
                    onClick={() => onDeleteAttachment(comment.id)}
                    className="p-1 text-gray-500 hover:text-red-400"
                  >
                    <Trash2 className="w-3 h-3" />
                  </button>
                </div>
                <p className="text-sm text-gray-300">{comment.text}</p>
              </div>
            ))}

            {/* Add Comment */}
            <div className="pt-2">
              <textarea
                value={newItemContent}
                onChange={(e) => setNewItemContent(e.target.value)}
                placeholder="Add a comment..."
                className="w-full p-2 bg-gray-800 border border-gray-700 rounded text-sm text-gray-200 placeholder-gray-500 focus:outline-none focus:border-blue-500"
                rows={2}
              />
              <button
                onClick={handleAddComment}
                disabled={!newItemContent.trim()}
                className="mt-2 flex items-center gap-1 px-3 py-1.5 text-sm bg-blue-600 hover:bg-blue-700 disabled:bg-gray-700 disabled:text-gray-500 text-white rounded transition-colors"
              >
                <Plus className="w-4 h-4" />
                Add Comment
              </button>
            </div>
          </div>
        )}
      </div>

      {/* Quick Actions Footer */}
      <div className="border-t border-gray-700 p-2">
        <div className="flex flex-wrap gap-1">
          <button
            className="flex items-center gap-1 px-2 py-1 text-xs text-gray-400 hover:text-white hover:bg-gray-800 rounded"
            onClick={() => setActiveTab('notes')}
          >
            <FileText className="w-3 h-3" />
            <span>N</span>
          </button>
          <button
            className="flex items-center gap-1 px-2 py-1 text-xs text-gray-400 hover:text-white hover:bg-gray-800 rounded"
            onClick={() => setActiveTab('todos')}
          >
            <CheckSquare className="w-3 h-3" />
            <span>T</span>
          </button>
          <button
            className="flex items-center gap-1 px-2 py-1 text-xs text-gray-400 hover:text-white hover:bg-gray-800 rounded"
            onClick={() => setActiveTab('callouts')}
          >
            <MessageSquare className="w-3 h-3" />
            <span>C</span>
          </button>
          <button
            className="flex items-center gap-1 px-2 py-1 text-xs text-gray-400 hover:text-white hover:bg-gray-800 rounded"
            onClick={() => setActiveTab('comments')}
          >
            <MessageCircle className="w-3 h-3" />
            <span>/</span>
          </button>
        </div>
      </div>
    </div>
  );
}

function getCalloutColor(type: CalloutType): string {
  switch (type) {
    case 'info': return '#3b82f6';
    case 'warning': return '#eab308';
    case 'opportunity': return '#22c55e';
    case 'pain_point': return '#f97316';
    case 'critical': return '#ef4444';
    default: return '#6b7280';
  }
}

function getCalloutStyles(type: CalloutType): string {
  switch (type) {
    case 'info': return 'bg-blue-900/20 border-blue-500';
    case 'warning': return 'bg-yellow-900/20 border-yellow-500';
    case 'opportunity': return 'bg-green-900/20 border-green-500';
    case 'pain_point': return 'bg-orange-900/20 border-orange-500';
    case 'critical': return 'bg-red-900/20 border-red-500';
    default: return 'bg-gray-800 border-gray-600';
  }
}

function getCalloutIcon(type: CalloutType) {
  const iconClass = 'w-4 h-4 mt-0.5';
  switch (type) {
    case 'info': return <Info className={`${iconClass} text-blue-400`} />;
    case 'warning': return <AlertTriangle className={`${iconClass} text-yellow-400`} />;
    case 'opportunity': return <Lightbulb className={`${iconClass} text-green-400`} />;
    case 'pain_point': return <AlertCircle className={`${iconClass} text-orange-400`} />;
    case 'critical': return <AlertTriangle className={`${iconClass} text-red-400`} />;
    default: return <Info className={`${iconClass} text-gray-400`} />;
  }
}

export default AttachmentPanel;
