#!/bin/bash

# Auto-Build Environment Setup for OAuth 2.0 + PKCE Authentication
# Generated by Planner Agent

set -e

echo "========================================"
echo "OAuth 2.0 + PKCE Authentication Setup"
echo "========================================"

# Colors
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m'

# Get script directory
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_ROOT="$(cd "${SCRIPT_DIR}/../../.." && pwd)"

echo "Project root: ${PROJECT_ROOT}"

# ============================================
# CHECK PREREQUISITES
# ============================================

echo ""
echo "Checking prerequisites..."

# Check Python version
if command -v python3 &> /dev/null; then
    PYTHON_VERSION=$(python3 --version 2>&1 | cut -d' ' -f2)
    echo -e "${GREEN}Python: ${PYTHON_VERSION}${NC}"
else
    echo -e "${RED}Python 3 not found${NC}"
    exit 1
fi

# Check if port 8487 is available (required for OAuth callback)
if lsof -i :8487 &> /dev/null; then
    echo -e "${RED}Port 8487 is in use - OAuth callback server cannot start${NC}"
    echo "Please free up port 8487 before running OAuth flow"
    exit 1
else
    echo -e "${GREEN}Port 8487 is available${NC}"
fi

# ============================================
# SETUP BACKEND VIRTUAL ENVIRONMENT
# ============================================

echo ""
echo "Setting up backend environment..."

BACKEND_DIR="${PROJECT_ROOT}/apps/backend"

# Check if venv exists
if [ ! -d "${BACKEND_DIR}/.venv" ]; then
    echo "Creating virtual environment..."
    cd "${BACKEND_DIR}"
    python3 -m venv .venv
fi

# Activate venv
source "${BACKEND_DIR}/.venv/bin/activate"

# Install dependencies
echo "Installing dependencies..."
cd "${BACKEND_DIR}"
pip install -q -r requirements.txt

# Check for Authlib (needed for OAuth)
if python -c "import authlib" 2>/dev/null; then
    echo -e "${GREEN}Authlib is installed${NC}"
else
    echo -e "${YELLOW}Authlib not found - adding to requirements${NC}"
    echo "" >> requirements.txt
    echo "# OAuth 2.0 + PKCE support" >> requirements.txt
    echo "Authlib>=1.3.0" >> requirements.txt
    pip install Authlib>=1.3.0
fi

# ============================================
# VERIFY EXISTING AUTH SETUP
# ============================================

echo ""
echo "Verifying existing authentication..."

# Check if existing auth module imports work
if python -c "from core.auth import get_auth_token, get_token_from_keychain" 2>/dev/null; then
    echo -e "${GREEN}Existing auth module OK${NC}"
else
    echo -e "${RED}Existing auth module has issues${NC}"
    exit 1
fi

# Check if macOS Keychain is accessible
if [ "$(uname)" == "Darwin" ]; then
    if python -c "
import platform
if platform.system() == 'Darwin':
    print('macOS detected')
" 2>/dev/null; then
        echo -e "${GREEN}macOS platform - Keychain available${NC}"
    fi
else
    echo -e "${YELLOW}Non-macOS platform - Keychain storage unavailable${NC}"
fi

# ============================================
# SUMMARY
# ============================================

echo ""
echo "========================================"
echo "Environment Ready!"
echo "========================================"
echo ""
echo "Next Steps:"
echo "  1. Implement oauth_server.py (callback server on port 8487)"
echo "  2. Implement oauth.py (PKCE flow with Authlib)"
echo "  3. Add save_token_to_keychain to auth.py"
echo "  4. Create tests in test_oauth.py"
echo ""
echo "OAuth Configuration:"
echo "  Authorization: https://console.anthropic.com/oauth/authorize"
echo "  Token:         https://console.anthropic.com/oauth/token"
echo "  Callback:      http://127.0.0.1:8487/oauth/callback"
echo "  Scopes:        org:createapikey user:profile user:inference"
echo ""
echo "To run the build:"
echo "  source auto-claude/.venv/bin/activate"
echo "  python auto-claude/run.py --spec 036"
echo ""
